name: mind_map
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_secure_storage: ^9.2.2
  bloc: ^8.1.4
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  connectivity_plus: ^6.0.5
  email_validator: ^3.0.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.4.1
  flutter_graph_view: ^1.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  lint: ^2.0.0

flutter:
  uses-material-design: true
